# Generated by Django 5.1.4 on 2024-12-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tag',
        ),
        migrations.AddField(
            model_name='video',
            name='tag',
            field=models.ManyToManyField(related_name='videos', to='videos.tag'),
        ),
    ]
