# Generated by Django 5.1.4 on 2024-12-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_tag_video_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='views_count',
        ),
    ]
