# Generated by Django 5.1.4 on 2024-12-30 16:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_watchhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='channel',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_channels', to=settings.AUTH_USER_MODEL, verbose_name='subscribed'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='videos.channel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Is Public'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='playlistvideo',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_videos', to='videos.playlist', verbose_name='PlayList'),
        ),
        migrations.AlterField(
            model_name='playlistvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_videos', to='videos.video', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='audio_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], default='en', max_length=2, verbose_name='Audio Language'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('gaming', 'Gaming'), ('beauty & fashion', 'Beauty And Fashion'), ('vlogging', 'Vlogging'), ('education', 'Education'), ('comedy', 'Comedy'), ('science & technology', 'Science And Technology'), ('travel', 'Travel'), ('food', 'Food'), ('helth & wellness', 'Helth And Wellness'), ('DIY & how-to', 'Diy And How To'), ('news & politics', 'News And Politics'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('pets & animals', 'Pets And Animals'), ('bussiness & parenting', 'Bussiness And Parenting'), ('cars & vehicles', 'Cars And Vehicles'), ('art & design', 'Art And Design'), ('spiritual & religious', 'Spiritual And Religious')], max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.channel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='video',
            name='comments_enabled',
            field=models.BooleanField(default=True, verbose_name='Comments Enabled'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in seconds', verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Is Premium'),
        ),
        migrations.AlterField(
            model_name='video',
            name='license',
            field=models.CharField(choices=[('s', 'Standart YouTube License'), ('c', 'Creative Commons')], default='s', max_length=20, verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='video',
            name='related_videos',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='videos.video', verbose_name='Related Videos'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tag',
            field=models.ManyToManyField(db_index=True, related_name='videos', to='videos.tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='video/thumbnails/%Y/%m/%d', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='video/file/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'webm'])], verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='video',
            name='views_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Views Count'),
        ),
        migrations.AlterField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Unlisted', 'Unlisted')], default='Public', max_length=10, verbose_name='Visibility'),
        ),
        migrations.AlterModelTable(
            name='channel',
            table='channels',
        ),
        migrations.AlterModelTable(
            name='video',
            table='videos',
        ),
    ]
