# Generated by Django 5.1.4 on 2025-01-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_video_options_channel_subscribers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchhistory',
            name='duration_watched',
        ),
    ]
