# Generated by Django 5.1.4 on 2025-01-02 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_remove_watchhistory_duration_watched'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('subscription', 'Subscription'), ('video_upload', 'Video Upload')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('gaming', 'Gaming'), ('beauty & fashion', 'Beauty & Fashion'), ('vlogging', 'Vlogging'), ('education', 'Education'), ('comedy', 'Comedy'), ('science & technology', 'Science & Technology'), ('travel', 'Travel'), ('food', 'Food'), ('helth & wellness', 'Helth & Wellness'), ('DIY & how-to', 'Diy & How-to'), ('news & politics', 'News & Politics'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('pets & animals', 'Pets & Animals'), ('bussiness & parenting', 'Bussiness & Parenting'), ('cars & vehicles', 'Cars & Vehicles'), ('art & design', 'Art & Design'), ('spiritual & religious', 'Spiritual & Religious')], max_length=100, verbose_name='Category'),
        ),
    ]
