# Generated by Django 5.1.4 on 2025-01-03 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_searchhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('copyright', 'Copyright'), ('inappropriate_content', 'Inappropriate Content'), ('spam', 'Spam'), ('harassment', 'Harassment'), ('misleading', 'Misleading'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendning'), ('in_pending', 'In Pending'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video Report',
                'verbose_name_plural': 'Video Reports',
                'db_table': 'video_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
