# Generated by Django 5.1.4 on 2025-01-04 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_videoreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text="JSON object with links, e.g., {'twiter': 'url', 'instagram': 'url'}", null=True, verbose_name='Social Links'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='channel/avatar/%Y/%m/%d', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('subscription', 'Subscription'), ('video_upload', 'Video Upload'), ('video_deleted', 'Video Deleted')], max_length=50, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_object_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Related Object ID'),
        ),
        migrations.AlterField(
            model_name='videoreport',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='videoreport',
            name='report_type',
            field=models.CharField(choices=[('copyright', 'Copyright'), ('inappropriate_content', 'Inappropriate Content'), ('spam', 'Spam'), ('harassment', 'Harassment'), ('misleading', 'Misleading'), ('other', 'Other')], default='other', max_length=50, verbose_name='Report Type'),
        ),
        migrations.AlterField(
            model_name='videoreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendning'), ('in_pending', 'In Pending'), ('resolved', 'Resolved')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
