# Generated by Django 5.1.4 on 2025-01-04 15:36

import apps.videos.models.stream
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_channel_social_links_alter_channel_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('stream_key', models.CharField(default=apps.videos.models.stream.generate_stream_key, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('sheduled', 'Sheduled'), ('live', 'Live'), ('finished', 'Finished')], default='sheduled', max_length=10)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Stream',
                'verbose_name_plural': 'Live Streams',
                'db_table': 'live_streams',
            },
        ),
    ]
