# Generated by Django 5.1.4 on 2025-01-04 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_livestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='streams/audios/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'flac'])], verbose_name='Audo File'),
        ),
        migrations.AddField(
            model_name='livestream',
            name='messages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='streams/videos/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'webm'])], verbose_name='Video File'),
        ),
    ]
