# Generated by Django 5.1.4 on 2024-12-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_berthd',
            field=models.DateField(blank=True, null=True),
        ),
    ]
