# Generated by Django 5.1.4 on 2024-12-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_date_of_berthd'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('f', 'Famale'), ('m', 'Male')], max_length=1, null=True),
        ),
    ]
